export const HANDLE_PHONE_DETAIL = "HANDLE_PHONE_DETAIL"

export const HANDLE_CARTS = "HANDLE_CARTS"

export const HANDLE_CARTS_QUANTITY = "HANDLE_CARTS_QUANTITY"

export const HANDLE_CARTS_DELETE = "HANDLE_CARTS_DELETE"